spring.application.name=qc-order-manage


spring.datasource.url=jdbc:postgresql://localhost:5432/qc_order_managa_db
spring.datasource.username=demo
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true